# -*- coding: utf-8 -*-
"""Neural-Prophet.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kVZ1mYrTwZIVkfqn96vBotD9S1RVCe-C

First we install the neural prophet
[Website and Research Paper](https://neuralprophet.com/)
"""

!pip install neuralprophet

!pip install plotly

"""Import the necessary libraris

"""

import pandas as pd
from neuralprophet import NeuralProphet
from matplotlib import pyplot as plt
import pickle

df = pd.read_csv('weatherAUS.csv')
df.head()

df.info()

df.describe()

df.shape

df.Location.unique()

df.columns

melb = df[df['Location']=='Melbourne']
melb['Date'] = pd.to_datetime(melb['Date'])
melb.head()

plt.plot(melb['Date'], melb['Temp3pm'])
plt.show()

melb['Year'] = melb['Date'].apply(lambda x: x.year)
melb = melb[melb['Year']<=2015]
plt.plot(melb['Date'], melb['Temp3pm'])
plt.show()

data = melb[['Date', 'Temp3pm']]
data.dropna(inplace=True)
data.columns = ['ds', 'y']
data.head()

m = NeuralProphet()

model = m.fit(data, freq='D', epochs=1000)

future = m.make_future_dataframe(data, periods=900)
forecast = m.predict(future)
forecast.head()

plot1 = m.plot(forecast)

import plotly.graph_objects as go


m.plot(forecast)

plt2 = m.plot_components(forecast)

import plotly.graph_objects as go

fig_components = m.plot_components(forecast)

fig_components.show()

with open('saved_model.pkl', "wb") as f:
    pickle.dump(m, f)

del m

with open('saved_model.pkl', "rb") as f:
    m = pickle.load(f)

future = m.make_future_dataframe(data, periods=900)
forecast = m.predict(future)
forecast.head()

plot1 = m.plot(forecast)

m.plot(forecast)